---
- name: Apache Lab
  hosts: instance-03
  become: yes
  gather_facts: yes
  tasks:

  - name: apache present
    dnf:
      name: httpd
      state: present

  - name: firewall open - http(s)
    block:
      - firewalld:
          zone: public
          service: http
          state: enabled
          immediate: yes
          permanent: yes
      - firewalld:
          zone: public
          service: https
          state: enabled
          immediate: yes
          permanent: yes

  - name: hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ ansible_default_ipv4.address }} {{ item }}"
    loop:
      - host1.test
      - host2.test
      - host3.test
