---
- name: cowsay example
  hosts: all

  tasks:
    - name: cow says hi
      shell: cowsay
      register: result_list
      ignore_errors: true
    - name: Diag
      debug:
        var: result_list
