---
- name: NGINX Webserver
  hosts: instance-02
  become: true
  tasks:
    - name: Disable Nginx Module
      command:
        cmd: dnf module disable -y nginx
        warn: false
    - name: Repository Configuration
      yum_repository:
        name: nginxrepo
        description: Official Nginx Repository
        baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
        gpgkey: https://nginx.org/packages/keys/nginx_signing.key
    - name: NGINX
      yum:
        name: '{{ nginx_packages }}'
        state: latest
        enablerepo: nginxrepo
        disable_gpg_check: true
      vars:
        nginx_packages:
          - nginx
          - nginx-module-geoip
          - nginx-module-njs
          - nginx-module-perl
          - nginx-module-xslt
    - name: Document Root Directory
      file:
        path: /srv/www
        mode: 0755
        owner: nginx
        group: nginx
        state: directory
    - name: Document Root Configuration
      replace:
        path: /etc/nginx/conf.d/default.conf
        regexp: '\/srv\/www'
        replace: /usr/share/nginx/html
        backup: yes
      notify: restartnginx

  handlers:
    - name: restart nginx
      listen: restartnginx
      systemd:
        name: nginx
        state: restarted
