---
- name: "User Loop"
  hosts: all
  become: yes
  vars:
    student:
      jdoe:
        first_name: John
        last_name: Doe
        itgilde_member: yes
      jroe:
        first_name: Jane
        last_name: Roe
        itgilde_member: no

  tasks:
    - name: show users
      debug:
        msg: "User {{ item }}"
      with_items:
        - "{{ student }}"
