---
- name: "Samba Public Share"
  hosts: instance-02
  become: true
  become_user: root
  remote_user: student
  tasks:
    - name: "Samba Public Share"
      block: 
        - name: directory /srv/samba_pub
          file:
            path: /srv/samba_pub
            owner: root
            group: root
            mode: 0777
            setype: public_content_rw_t
            state: directory
        - name: "SELinux Policy Samba Public Share"
          seboolean: 
            name: smbd_anon_write 
            persistent: yes
            state: yes
        - name: "SELinux Policy"
          sefcontext:
            target: /srv/samba_pub(/.*)?
            setype: public_content_rw_t
            state: present
        - name: "Share definition"
          blockinfile:
            path: /etc/samba/smb.conf
            backup: yes
            state: present
            validate: testparm -s %s
            block: | 
              [public]
                      comment = Public Share
                      path = /srv/samba_pub
                      writable = yes
                      browseable = yes
                      printable = no
                      guest ok = yes
          notify: share_added
  handlers:
    - name: "Restart Samba"
      listen: share_added
      systemd:
        name: smb.service
        state: restarted

